version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discodeit-app
    depends_on:
      db:
        condition: service_healthy    #db 컨테이너가 "헬스체크 통과" 상태일때 app실행
    ports:
      - "${APP_PORT}:80"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      # BinaryContentStorage 경로
      BINARY_CONTENT_STORAGE_PATH: ${BINARY_CONTENT_STORAGE_PATH}
    volumes:
      - binary-content-data:${BINARY_CONTENT_STORAGE_PATH}
    restart: unless-stopped
    image: discodeit:local

  db:
    image: postgres:16
    container_name: discodeit-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #DB가 container화 되면 DataGrip(외부)에서 접근에 제한되기 때문에 port를 설정해서 접근하도록 함.
    ports:
      - "${DB_PORT}:5432"

    #DB 데이터는 /var/lib/postgresql/data에 저장
    # 실제로는 Docker volume(postgres-data)에 영속화
    volumes:
      - postgres-data:/var/lib/postgresql/data

      #DB 최초 실행시 schema.sql 자동 실행
      #내 pc의 schema.sql파일을 컨테이너 안 /docker-entrypoint-initdb.d/01-schema.sql로 연결해서 PostgreSQL이 실행 할 수 있게 한다.
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  binary-content-data:
  postgres-data: