discodeit:
  storage:
    type: local
    local:
      root-path: ./discodeit-storage

spring:
  application:
    name: discodeit
  profiles:
    active: dev # 기본적으로 dev 환경 활성화

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100

logging:
  level:
    root: info

    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.transaction.interceptor: TRACE
    org.springframework.transaction.support.AbstractPlatformTransactionManager: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: TRACE
    org.springframework.orm.jpa: DEBUG