spring:
  datasource:
    url: jdbc:h2:mem:discodeit;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true            # 웹 콘솔 사용 하기
      path: /h2-console        # 접속 주소
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  boot:
    admin:
      client:
        url: http://localhost:9090

logging:
  level:
    com.sprint.mission.discodeit: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace #버전 올라가면서 경로에 orm추가 해야해야 바인딩 파라미터 보임
    org.springframework.security: trace

server:
  port: 8080

jwt:
  secreteKey: ${JWT_SECRETE_KEY:thisisjwtsecretekeyfordiscodeitservice}