spring:
  application:
    name: discodeit
  profiles:
    active: dev
  cache:
    caffeine:
      spec: >
        maximumSize=100,
        expireAfterAccess=600s,
        recordStats
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: discodeit-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
logging:
  level:
    org.springframework.security: DEBUG
admin:
  init:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420