server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit_prod
    username: discodeit_prod_user
    password: prod_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: info
    org.hibernate.SQL: info