# 공통 환경 설정 파일

# 프로젝트 기본 설정
spring:
  application:
    name: discodeit                                       # 프로젝트 고유 이름
  profiles:
    active: dev
  boot:
    admin:
      client:
        instance:
          name: discodeit
  cache:
    type: caffeine
    cache-names:
      - channels
      - notifications
      - users
    caffeine:
      # 최대 100개 저장, 접근 후 10분(600초) 지나면 만료, 통계 기록 활성화
      spec: maximumSize=100, expireAfterAccess=600s, recordStats

# JWT 설정
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

## 로깅 설정 값
#logging:
#  level:
#    root: info                                            # 프로젝트 전체에서 로그를 핵심 정보 위주로 출력하도록 설정

# Swagger 설정 값
springdoc:
  api-docs:
    enabled: true                                         # API 명세서 자동 생성 활성화
    path: /api-docs                                       # 생성된 API 명세서의 저장 경로

  swagger-ui:
    enabled: true                                         # 웹 브라우저 내 Swagger UI 활성화
    path: /docs                                           # Swagger UI 접속 주소
    groups-order: DESC                                    # API 그룹 내림차순 정렬
    operations-sorter: method                             # HTTP 메서드 순서대로 API 정렬

  default-consumes-media-type: application/json           # 기본 요청 형식 = JSON
  default-produces-media-type: application/json           # 기본 응답 형식 = JSON

# Actuator 설정
management:
  endpoints:
    web:
      exposure: # 웹에 노출시킬 Endpoint 지정
        include: "health, info, metrics, loggers"         # 건강 상태, 앱 정보, 성능 수치, 로그 설정

  endpoint:
    health:
      show-details: always                                # 항상 상세한 health 결과 표시

  info:
    env:
      enabled: true

  observations:
    annotations:
      enabled: true

# 애플리케이션 상세 정보
info:
  app:
    name: "Discodeit"                                     # 애플리케이션 이름
    version: "1.7.0"                                      # 애플리케이션 버전
    java-version: "17"                                    # 자바 버전
    spring-boot-version: "3.4.0"                          # 스프링 부트 버전
  # 주요 설정 정보
  major-config:
    datasource:
      url: "${spring.datasource.url}"
      driver-class-name: "${spring.datasource.driver-class-name}"

    jpa:
      ddl-auto: "${spring.jpa.hibernate.ddl-auto}"

    storage:
      type: "LOCAL"
      path: "./uploads"

    multipart:
      max-file-size: "10MB"
      max-request-size: "10MB"