spring:
  application:
    name: discodeit

  profiles:
    active: dev

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  sql:
    init:
      mode: always
      encoding: UTF-8

  jpa:
    open-in-view: false

discodeit:
  storage:
    type: local
    local:
      root-path: ./storage

logging:
  level:
    root: info