discodeit:
  repository:
    type: file # jcf | file
    file-directory: .discodeit

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/discodeit}
    username: ${SPRING_DATASOURCE_USERNAME:discodeit_user}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.sprint.mission.discodeit: INFO
    org.springframework.transaction: OFF
    org.hibernate: WARN
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
