DROP TABLE IF EXISTS binary_contents CASCADE;
DROP TABLE IF EXISTS MESSAGE_ATTACHMENTS CASCADE;
DROP TABLE IF EXISTS READ_STATUSES CASCADE;
DROP TABLE IF EXISTS MESSAGES CASCADE;
DROP TABLE IF EXISTS USER_STATUSES CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS CHANNELS CASCADE;

CREATE TABLE BINARY_CONTENTS(
    id UUID PRIMARY KEY ,
    created_at TIMESTAMPTZ NOT NULL ,
    file_name VARCHAR(255) NOT NULL ,
    size BIGINT NOT NULL ,
    content_type VARCHAR(100) NOT NULL
);

CREATE TABLE USERS (
    id UUID PRIMARY KEY ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    username VARCHAR(50) NOT NULL UNIQUE ,
    email VARCHAR(100) NOT NULL UNIQUE ,
    password VARCHAR(60) NOT NULL ,
    profile_id UUID UNIQUE ,
    FOREIGN KEY (profile_id) REFERENCES BINARY_CONTENTS(id) ON DELETE SET NULL

);

CREATE TABLE USER_STATUSES(
    id UUID PRIMARY KEY ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    user_id UUID UNIQUE NOT NULL ,
    last_active_at TIMESTAMPTZ NOT NULL ,
    FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE
);

CREATE TABLE CHANNELS(
    id UUID PRIMARY KEY ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    name VARCHAR(100),
    description VARCHAR(500),
    type VARCHAR(10) NOT NULL CHECK ( type IN ('PRIVATE','PUBLIC') )
);

CREATE TABLE MESSAGES(
    id UUID PRIMARY KEY ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    content TEXT NOT NULL,
    channel_id UUID NOT NULL,
    author_id UUID,
    FOREIGN KEY (channel_id) REFERENCES CHANNELS(id) ON DELETE CASCADE ,
    FOREIGN KEY (author_id) REFERENCES USERS(id) ON DELETE SET NULL
);

CREATE TABLE READ_STATUSES(
    id UUID PRIMARY KEY ,
    created_at TIMESTAMPTZ NOT NULL ,
    updated_at TIMESTAMPTZ,
    user_id UUID NOT NULL ,
    channel_id UUID NOT NULL ,
    last_read_at TIMESTAMPTZ NOT NULL ,
    UNIQUE (user_id,channel_id),
    FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE ,
    FOREIGN KEY (channel_id) REFERENCES CHANNELS(id) ON DELETE CASCADE
);



CREATE TABLE MESSAGE_ATTACHMENTS(
    message_id UUID NOT NULL ,
    attachment_id UUID NOT NULL ,
    FOREIGN KEY (message_id) REFERENCES MESSAGES(id) ON DELETE CASCADE ,
    FOREIGN KEY (attachment_id) REFERENCES BINARY_CONTENTS(id) ON DELETE CASCADE
);