worker_processes auto;
events {}

http {

  server {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      listen 3000;
      server_name localhost;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      location /api/ {
          proxy_pass http://discodeit-app:80;
      }

      # 웹소켓
      location /ws/ {
          proxy_pass http://discodeit-app:80;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
      }

      # 액츄에이터
      location /api/actuator/ {
        proxy_pass http://discodeit-app:80/actuator/;
      }

      # 정적파일
      location / {
        root /usr/share/nginx/html; # 저장 위치
        try_files $uri $uri/ /index.html; #경로 최초페이지로 바꾸기(SPA니까)
      }

  }
}
