name: CI - 빌드 및 테스트 커버리지 검사

# 언제 작업을 수행할 것인지 (Trigger)
on:
  push:
    branches: [ "sprint8" ] # sprint8 브랜치에 푸시될 때마다 실행

#on: # 심화 요구사항, 추후 제출 시 수정 예정
#  pull_request:
#    branches: [ "main" ] # main 브랜치로 PR이 올라올 때만 실행

# 어떤 환경에서 작업할 것인지 (Job Setup)
jobs:
  test:
    runs-on: ubuntu-latest # 깃허브가 제공하는 최신 우분투 서버에서 실행

    steps:
      # Step 1: 깃허브 저장소의 코드를 우분투 서버로 다운로드
      - name: 저장소 코드 가져오기 (Checkout)
        uses: actions/checkout@v4

      # Step 2: 요구사항에 맞춘 Java 17 (Amazon Corretto) 설치
      - name: JDK 17 환경 설정 (Amazon Corretto)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      # Step 3: 우분투 서버에서 gradlew 파일을 실행할 수 있도록 권한 부여
      - name: Gradle Wrapper 실행 권한 부여
        run: chmod +x gradlew

      # Step 4: 코드를 빌드하고 테스트 실행
      - name: 애플리케이션 빌드 및 테스트 실행
        run: ./gradlew build
        env:
          AWS_S3_ACCESS_KEY: ${{ secrets.AWS_S3_ACCESS_KEY }}
          AWS_S3_SECRET_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}
          AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

      # Step 5: 테스트가 끝나면 Codecov로 커버리지(테스트 통과율) 리포트 전송
      - name: Codecov에 테스트 커버리지 결과 업로드
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}